/-
Copyright (c) 2026 Denise M. Case.
Released under MIT license as described in the file LICENSE.
Authors: Denise M. Case
-/
module

public import SE.Persistence.Relation.Survival

set_option autoImplicit false

/-!
# Identity Equivalence

SE.Persistence.Relation.Equivalence

The identity relation `~_P` of a classification: the equivalence relation
generated by the steps of preserving transformations.

It depends on a classification only through its preserving set, so forgetting
applicability (`Classification.coarse`) does not change it.

On the free dynamics it is characterized exactly: a transformation's private
pair is identity-related precisely when the transformation preserves.
-/

namespace SE.Persistence

@[expose] public section

variable {T C : Type}

-- RR.DEFINES: PS.DEF.IDENTITY_REL
/-- The identity relation `~_P`. -/
def Classification.identityRel (c : Classification T) (d : Dynamics T C) :
    C → C → Prop :=
  Generated (c.stepRel d)

-- RR.DEFINES: PS.THM.IDENTITY_REL_EQUIVALENCE
/-- `~_P` is an equivalence relation. -/
theorem Classification.identityRel_equivalence (c : Classification T)
    (d : Dynamics T C) : Equivalence (c.identityRel d) :=
  Generated.equivalence _

-- RR.DEFINES: PS.THM.SURVIVES_IDENTITY_REL
/-- Survival implies identity. -/
theorem Classification.survives_identityRel {c : Classification T}
    {d : Dynamics T C} {x y : C} (h : c.Survives d x y) :
    c.identityRel d x y :=
  Reach.toGenerated h

-- RR.DEFINES: PS.THM.IDENTITY_REL_MONO
/-- A larger preserving set generates a larger identity relation. -/
theorem Classification.identityRel_mono {c c' : Classification T}
    (d : Dynamics T C) (h : ∀ t, c.IsPrs t → c'.IsPrs t) {x y : C}
    (hg : c.identityRel d x y) : c'.identityRel d x y :=
  Generated.mono
    (fun _ _ ⟨t, ht, hs⟩ => ⟨t, h t ht, hs⟩) hg

-- RR.DEFINES: PS.THM.IDENTITY_REL_EQ_OF_PRS_IFF
/-- Equal preserving sets give equal identity relations on every dynamics. -/
theorem Classification.identityRel_eq_of_prs_iff {c c' : Classification T}
    (d : Dynamics T C) (h : ∀ t, c.IsPrs t ↔ c'.IsPrs t) :
    c.identityRel d = c'.identityRel d := by
  funext x y
  apply propext
  exact ⟨identityRel_mono d (fun t => (h t).1),
    identityRel_mono d (fun t => (h t).2)⟩

-- RR.DEFINES: PS.THM.IDENTITY_REL_EQ_OF_COARSE_EQ
/--
Classifications with the same coarse matrix have the same identity relation on
every dynamics. Forgetting applicability does not change `~_P`.
-/
theorem Classification.identityRel_eq_of_coarse_eq {c c' : Classification T}
    (d : Dynamics T C) (h : ∀ t, c.coarse t = c'.coarse t) :
    c.identityRel d = c'.identityRel d :=
  Classification.identityRel_eq_of_prs_iff d fun t => by
    rw [← Classification.coarse_eq_prs_iff, ← Classification.coarse_eq_prs_iff, h t]

/-- Invariant of the identity relation on the free dynamics. -/
private def FreeInv (c : Classification T) (x y : T × Bool) : Prop :=
  x = y ∨ ∃ s, c.IsPrs s ∧
    ((x = (s, false) ∧ y = (s, true)) ∨ (x = (s, true) ∧ y = (s, false)))

/-- `FreeInv` is an equivalence relation. -/
private theorem FreeInv.equivalence (c : Classification T) :
    Equivalence (FreeInv c) := by
  refine ⟨fun x => Or.inl rfl, ?_, ?_⟩
  · intro x y h
    rcases h with h | ⟨s, hs, h | h⟩
    · exact Or.inl h.symm
    · exact Or.inr ⟨s, hs, Or.inr ⟨h.2, h.1⟩⟩
    · exact Or.inr ⟨s, hs, Or.inl ⟨h.2, h.1⟩⟩
  · intro x y z hxy hyz
    rcases hxy with rfl | ⟨s, hs, ⟨h1, h2⟩ | ⟨h1, h2⟩⟩
    · exact hyz
    · rcases hyz with rfl | ⟨s', hs', ⟨h3, h4⟩ | ⟨h3, h4⟩⟩
      · exact Or.inr ⟨s, hs, Or.inl ⟨h1, h2⟩⟩
      · subst h2; simp at h3
      · subst h2
        have : s = s' := by simpa using h3
        subst this
        exact Or.inl (h1.trans h4.symm)
    · rcases hyz with rfl | ⟨s', hs', ⟨h3, h4⟩ | ⟨h3, h4⟩⟩
      · exact Or.inr ⟨s, hs, Or.inr ⟨h1, h2⟩⟩
      · subst h2
        have : s = s' := by simpa using h3
        subst this
        exact Or.inl (h1.trans h4.symm)
      · subst h2; simp at h3

-- RR.DEFINES: PS.THM.IDENTITY_REL_FREE_IFF
/--
On the free dynamics, `~_P` relates a transformation's private pair exactly
when the transformation preserves.
-/
theorem Classification.identityRel_free_iff (c : Classification T) (t : T) :
    c.identityRel (freeDynamics T) (t, false) (t, true) ↔ c.IsPrs t := by
  constructor
  · intro h
    have hinv : FreeInv c (t, false) (t, true) :=
      Generated.le_of_equivalence (FreeInv.equivalence c)
        (fun x y ⟨s, hs, hx, hy⟩ => Or.inr ⟨s, hs, Or.inl ⟨hx, hy⟩⟩) h
    rcases hinv with h | ⟨s, hs, ⟨h1, _⟩ | ⟨h1, _⟩⟩
    · simp at h
    · have : t = s := by simpa using h1
      subst this
      exact hs
    · simp at h1
  · intro h
    exact Generated.rel ⟨t, h, rfl, rfl⟩

end

end SE.Persistence
