/-
Copyright (c) 2026 Denise M. Case.
Released under MIT license as described in the file LICENSE.
Authors: Denise M. Case
-/
module

set_option autoImplicit false

/-!
# Dynamics and Generated Relations

SE.Persistence.Relation.Generated

Dynamics, and the two closures built from a step relation:

- `Reach r`: the reflexive-transitive closure, directed;
- `Generated r`: the equivalence closure, symmetric.

This module is generic. It knows nothing of classifications; later modules
apply the closures to the steps of preserving transformations.

A `Dynamics` says how transformations act on a carrier. This module does not
say what the carrier is.
-/

namespace SE.Persistence

@[expose] public section

variable {T C : Type}

-- RR.DEFINES: PS.TYPE.DYNAMICS
/--
How each transformation relates states of a carrier `C`:
`step t x y` means `y` is a result of applying `t` to `x`.
-/
structure Dynamics (T C : Type) where
  /-- `step t x y`: `y` is a result of applying `t` to `x`. -/
  step : T → C → C → Prop

-- RR.DEFINES: PS.DEF.FREE_DYNAMICS
/--
The free dynamics: each transformation `t` relates one private pair of
states, `(t, false)` to `(t, true)`, and nothing else.
-/
def freeDynamics (T : Type) : Dynamics T (T × Bool) where
  step t x y := x = (t, false) ∧ y = (t, true)

-- RR.DEFINES: PS.TYPE.REACH
/-- The reflexive-transitive closure of `r`, from a fixed start `x`. -/
inductive Reach {C : Type} (r : C → C → Prop) (x : C) : C → Prop where
  | refl : Reach r x x
  | tail {y z : C} : Reach r x y → r y z → Reach r x z

/-- One step is a reach. -/
theorem Reach.single {r : C → C → Prop} {x y : C} (h : r x y) : Reach r x y :=
  Reach.tail Reach.refl h

/-- Reach is transitive. -/
theorem Reach.trans {r : C → C → Prop} {x y z : C}
    (h1 : Reach r x y) (h2 : Reach r y z) : Reach r x z := by
  induction h2 with
  | refl => exact h1
  | tail _ hr ih => exact Reach.tail ih hr

/-- Reach is monotone in the step relation. -/
theorem Reach.mono {r s : C → C → Prop} (h : ∀ x y, r x y → s x y) {x y : C}
    (hr : Reach r x y) : Reach s x y := by
  induction hr with
  | refl => exact Reach.refl
  | tail _ hr ih => exact Reach.tail ih (h _ _ hr)

-- RR.DEFINES: PS.TYPE.GENERATED
/-- The equivalence relation generated by `r`. -/
inductive Generated {C : Type} (r : C → C → Prop) : C → C → Prop where
  | rel {x y : C} : r x y → Generated r x y
  | refl (x : C) : Generated r x x
  | symm {x y : C} : Generated r x y → Generated r y x
  | trans {x y z : C} : Generated r x y → Generated r y z → Generated r x z

/-- `Generated r` is an equivalence relation. -/
theorem Generated.equivalence (r : C → C → Prop) : Equivalence (Generated r) :=
  ⟨Generated.refl, Generated.symm, Generated.trans⟩

/-- `Generated r` is the least equivalence relation containing `r`. -/
theorem Generated.le_of_equivalence {r s : C → C → Prop}
    (hs : Equivalence s) (h : ∀ x y, r x y → s x y) {x y : C}
    (hg : Generated r x y) : s x y := by
  induction hg with
  | rel hxy => exact h _ _ hxy
  | refl x => exact hs.refl x
  | symm _ ih => exact hs.symm ih
  | trans _ _ ih1 ih2 => exact hs.trans ih1 ih2

/-- Generation is monotone in the generating relation. -/
theorem Generated.mono {r s : C → C → Prop}
    (h : ∀ x y, r x y → s x y) {x y : C}
    (hg : Generated r x y) : Generated s x y :=
  Generated.le_of_equivalence (Generated.equivalence s)
    (fun a b hab => Generated.rel (h a b hab)) hg

/-- Every reach is a generated identity. -/
theorem Reach.toGenerated {r : C → C → Prop} {x y : C}
    (h : Reach r x y) : Generated r x y := by
  induction h with
  | refl => exact Generated.refl x
  | tail _ hr ih => exact Generated.trans ih (Generated.rel hr)

end

end SE.Persistence
